version: "3"
services: 
  flight-reservation:
    image: atharvahiwase7/flightreservationjenkins
    environment:
    - BROWSER
    - HUB_HOST=hub
    - THREAD_COUNT=1
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/flightreservation/test-output
